const axios = require('axios');

class TelegramService {
  constructor() {
    this.botToken = process.env.TELEGRAM_BOT_TOKEN;
    this.apiUrl = `https://api.telegram.org/bot${this.botToken}`;
    console.log('🤖 Telegram Service Started with Actual Bot');
  }

  async sendMessage(chatId, message) {
    try {
      console.log(`📤 Sending Telegram message to: ${chatId}`);
      
      const response = await axios.post(`${this.apiUrl}/sendMessage`, {
        chat_id: chatId,
        text: message,
        parse_mode: 'HTML'
      }, {
        timeout: 10000
      });
      
      console.log('✅ Telegram message sent successfully');
      return response.data;
    } catch (error) {
      console.error('❌ Telegram message failed:');
      console.error('Error:', error.response?.data || error.message);
      
      // Specific error handling
      if (error.response?.data?.description?.includes('chat not found')) {
        throw new Error('Invalid Chat ID. Please start the bot first.');
      }
      if (error.response?.data?.description?.includes('bot was blocked')) {
        throw new Error('You have blocked the bot. Please unblock and try again.');
      }
      
      throw new Error(`Telegram API error: ${error.response?.data?.description || error.message}`);
    }
  }

  async sendWebsiteSummary(chatId, website, monitoringData) {
    const { statistics, currentStats } = monitoringData;
    
    const message = `
🌐 <b>WEBSITE MONITORING SUMMARY</b>

<b>Website:</b> ${website.name}
<b>URL:</b> ${website.url}
<b>Status:</b> ${website.status === 'up' ? '🟢 UP' : '🔴 DOWN'}

<b>📊 PERFORMANCE METRICS</b>
• Uptime: ${statistics.uptimePercentage}%
• Response Time: ${currentStats.avgResponseTime}ms
• Performance Score: ${currentStats.performanceScore}/100
• SEO Score: ${currentStats.seoScore}/100

<b>📈 MONITORING STATS</b>
• Total Checks: ${statistics.totalChecks}
• Successful: ${statistics.upChecks}
• Failed: ${statistics.downChecks}
• Last Check: ${website.lastChecked ? new Date(website.lastChecked).toLocaleString() : 'Never'}

${website.status === 'down' ? '🚨 <b>ALERT: Website is currently DOWN!</b>' : '✅ All systems operational!'}

<i>Generated by AI Website Monitor</i>
    `.trim();

    return await this.sendMessage(chatId, message);
  }
}

module.exports = new TelegramService();